development:
  adapter: postgresql
  encoding: unicode
  database: green_bull_development
  pool: 5
  username: alex
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: green_bull_test
  pool: 5
  username: alex
  password: password
