# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 984f7d56d5659076158d2ccd341d15bf3778c46d10ac9e16f11e37650ae729bb2d941c166daa9faef3feeebebf562525a803135147b38bd8c9ecb81fb442729f

test:
  secret_key_base: aa8c3f25a63c44c3c68bcf201fca8a0aaae8dee2a334fc5a628fa39818866dc498dc135a9f467fdee902b42a978197d98fa2e694c75222169531f0e20ad1c037

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
